CREATE SCHEMA currency_limit
CREATE TABLE currency_limit."limit"
    (
        id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        limit_value         DOUBLE PRECISION,
        limit_balance       DOUBLE PRECISION,
        expense_category    VARCHAR(255),
        date_time_create    TIMESTAMP WITHOUT TIME ZONE,
        actual      BOOLEAN,
        currency_short_name VARCHAR(255),
        CONSTRAINT pk_limit PRIMARY KEY (id)
    );
CREATE TABLE currency_limit.transaction
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    account_from        BIGINT,
    account_to          BIGINT,
    currency_short_name VARCHAR(255),
    sum                 DOUBLE PRECISION,
    date_time_create    TIMESTAMP WITHOUT TIME ZONE,
    limit_exceeded      BOOLEAN,
    expense_category    VARCHAR(255),
    limit_id            BIGINT,
    CONSTRAINT pk_transaction PRIMARY KEY (id)
);

ALTER TABLE currency_limit.transaction
    ADD CONSTRAINT FK_TRANSACTION_ON_LIMIT FOREIGN KEY (limit_id) REFERENCES currency_limit."limit" (id);
